manifest:
  defaults:
    revision: v0.2

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-nice-view
      remote: zmkfirmware
      revision: main
      path: app/lib/zmk-nice-view

  self:
    path: config